#!/bin/ash
#
# setup
#
# Configure the Lan Box
#
# This has to be written pretty much entirely with shell
# and expr.  We don't have room for anything else

# This should just fall to the second option.
# Former is for development . . .
RWD=../../../RW.example
if [ -d $RWD ]
then
    CFGDIR=$RWD
elif [ -d /etc/conf ]
then
    CFGDIR=/etc/conf
else
    CFGDIR=../../etc/rw
fi

export CFGDIR

PATH=/usr/bin:/bin:/usr/sbin:/sbin
export PATH

#----------------------------------------------------------------------
# MENU
#----------------------------------------------------------------------
menu()
{
    runlevel=`cat $CFGDIR/runlevel`

    sel2=
    sel3=
    sel4=
    case "$runlevel" in
        2) sel2="SELECTED" ;;
        3) sel3="SELECTED" ;;
        4) sel4="SELECTED" ;;
    esac

#    echo "<pre>`set`</pre>";
    echo -e "

<form method=POST action="/cgi-bin/setup">
<input type=hidden name=\"last_menu\" value=\"main\">
<table>
<th>Running As</th>
<td>
  <select name=\"runlevel\">
  <option value=\"2\" $sel2>Station/Router
  <option value=\"3\" $sel3>AP/Bridge
  <option value=\"4\" $sel4>AP/Router
  </select>
</td>
</table>

<br>
<input type=submit name=submit value=\"OK\">
<br>

<h3>Select Configuration Item</h3>

<table>
"

    for script in *
    do
        case "$script" in
          setup) : ;;
          *) ./$script option ;;
        esac
    done

    echo -e "
</table>
<br>
Click SAVE to commit changes<br>
<input type=submit name=submit value=\"SAVE\">

</form>
"
}


#----------------------------------------------------------------------
# HEADER
#----------------------------------------------------------------------
header()
{
    echo -e "\
Content-Type: text/html

"
    case "$1" in
      save) 
    echo -e "\
<META HTTP-EQUIV=REFRESH CONTENT=\"70; URL=/index.html\">
<html>
<body background=/linuxap.png>
<center>
<h2>SAVING CONFIGURATION</h2>
</center>
<hr>
"
        ;;
      status)
        ./$1 header
        ;;
      *)
    echo -e "\
<html>
<body background=/linuxap.png>
<center>
<h2>OpenSTA Setup Screen</h2>
</center>
<hr>
"
        ;;
    esac
}

#----------------------------------------------------------------------
# MAIN
#----------------------------------------------------------------------
input=`echo "$QUERY_STRING" | tr '&' ' '`

cfg=
if [ "$input" = "" ]
then
    input=$CGI_ARGLIST_
fi
if [ "$input" != "" ]
then
    for var in $input
    do
        case "$var" in
          cfg-*) cfg=`expr "$var" : "cfg-\\(.*\\)\\."`
            ;;
        esac
    done
fi


case "$CGI_submit" in
  OK)
    ./$CGI_last_menu write ;;
  CANCEL|RETURN)
    : ;;
  SAVE) header save
    echo "<pre>"
    /bin/save_config
    echo "</pre>
<h3><center><blink>
Rebooting, takes about 60 seconds
</blink></center><h3></html>"
    /sbin/reboot
    sleep 10
    ;;
  GO) : ;;
esac

header $cfg

if [ "$cfg" = "" ]
then
    menu
else
    ./$cfg menu
fi

echo "</html>"
