#!/bin/sh
#
# tcpsrv
#
[ -f $CFGD/netcfg ] && . $CFGD/netcfg

case "$1" in
start|2|3|4)
    echo "Set date && start logging."
    [ ! -z "$timehost" ] && rdate -s $timehost
    [ ! -z "$logaddr" ] && syslogd -R $logaddr && klogd
    ;;
stop|0|1|6)
    [ ! -z "$logaddr" ] && killall klogd syslogd
    sleep 2
    ;;
restart)
    $0 stop
    $0 start
    ;;
esac
exit 0
